### ISSUE TITLE
Guide To Setup Project

### ISSUE THREAD

**Issue by TreciaKS** [cadentic/strapi-webdev#1]
Hey There

Can you write a step by step guide on how I can set up my project in my local machine so I can help you solve your code issues.

I've noticed that there are a lot of issues in your code, maybe, we can have a call and work through them together? :)

**Comment by cadentic** [comment]
[strapi-webdev/ ZETTADATEN is a strapi project](https://github.com/cadentic/strapi-webdev)/ZETTADATEN/ 
it works as data end point 
[next js project ](https://github.com/cadentic/strapi-webdev/tree/main/zettadaten_fe_next17) 

The rest of the part is nuxt js and laravel 9.x but they are not so far connected to strapi so you can ignore them for now.
backend database is mysql which is not supported by vercel 

so open the pwsh and 
cd .\ZETTADATEN\ 
npm install 
npm run build 
npm run dev

for [next js](https://github.com/cadentic/strapi-webdev/tree/main/zettadaten_fe_next17) this is the next js folder
npm install
npm run build 
npm run develop 

but as usual, you will not get my database structure to feed your mysql , to do so you need my database dump 🗡️ 

but if you would not bother about that if you can omit the Axios call in testimonial.js 
so the exact problem is in [testimonial.js](https://github.com/cadentic/strapi-webdev/blob/main/zettadaten_fe_next17/components/Testimonial.js) 

```
                        <CardMedia component="img" height="200" image="{requestMyImages.attributes.Images.data.attributes.formats.medium.url}" alt="Paella dish" />
```
this is not picking the images.


this testimonial.js file needs a database which is mysqldump 

the total project is time-consuming; I am trying to create a clone of www.oracle.com.

**Comment by TreciaKS** [comment]
Hey there

It's been a while. Apologies of not getting back sooner.

How is the project now? Is everything working as expected?
